import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Expander documentation sidebar
  expanderSidebar: [
    {
      type: "autogenerated",
      dirName: "expander",
    },
  ],
  // ExpChain documentation sidebar
  expchainSidebar: [
    {
      type: "autogenerated",
      dirName: "expchain",
    },
  ]
};

export default sidebars;
